apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jx-dev-cluster-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - pods/status
  - services
  - endpoints
  - configmaps
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  - events
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - deployments/status
  - statefulsets
  - statefulsets/status
  - daemonsets
  - daemonsets/status
  - replicasets
  - replicasets/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - jobs/status
  - cronjobs
  - cronjobs/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs: ["get", "list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelines", "taskruns", "tasks"]
  verbs: ["get", "list", "update", "patch"]
- apiGroups: ["jenkins.io"]
  resources: ["pipelineactivities"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["jenkins.io"]
  resources: ["sourcerepositories"]
  verbs: ["get", "list", "create", "update"]
- apiGroups: ["lighthouse.jenkins-x.io"]
  resources: ["lighthousejobs"]
  verbs: ["create"]
- apiGroups: ["lighthouse.jenkins-x.io"]
  resources: ["lighthousebreakpoints"]
  verbs: ["get", "list", "create", "delete"]
